name: Crawl Data Task

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Libraries
        run: |
          pip install -r requirements.txt
      - name: Execute Script
        run: |
          python index.py