name: Crawl Data Task

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create new Branch
        run: git checkout -B data-processing-branch
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Libraries
        run: |
          pip install -r requirements.txt
      - name: Execute Script
        run: |
          python index.py
      - name: Git Add Result
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add datas/
          git commit -m "Data crawled at \`$(date +'%Y-%m-%dT%H:%M:%S')\`"
          git push --set-upstream origin data-processing-branch
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: data-processing-branch
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
      - name: Delete PR Branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: data-processing-branch