name: Crawl Data Task

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create new Branch
        run: git checkout -B data-processing-branch
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Libraries
        run: |
          pip install -r requirements.txt
      - name: Execute Script
        run: |
          python index.py
      - name: Git Add Result
        run: |
          git config user.email "27856297+dependabot-preview[bot]@users.noreply.github.com"
          git config user.name "27856297+dependabot-preview[bot]"
          git add datas/
          git commit -m "Data crawled at \`{{$(date +'%Y-%m-%dT%H:%M:%S')}}\`"
          git push --set-upstream origin data-processing-branch